# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'questFinPestuse_Gui.ui'
#
# Created: Mon Mar 20 14:57:46 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(1100, 800)
        Dialog.setMinimumSize(QtCore.QSize(1100, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_numeroQuestion = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_numeroQuestion.setFont(font)
        self.label_numeroQuestion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_numeroQuestion.setObjectName(_fromUtf8("label_numeroQuestion"))
        self.horizontalLayout.addWidget(self.label_numeroQuestion)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_24.addWidget(self.label_13)
        self.lineEdit_age = QtGui.QLineEdit(Dialog)
        self.lineEdit_age.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_age.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_age.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_age.setMaxLength(2)
        self.lineEdit_age.setObjectName(_fromUtf8("lineEdit_age"))
        self.horizontalLayout_24.addWidget(self.lineEdit_age)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_24)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_31.addWidget(self.label_14)
        self.radioButton_sexeF = QtGui.QRadioButton(Dialog)
        self.radioButton_sexeF.setObjectName(_fromUtf8("radioButton_sexeF"))
        self.horizontalLayout_31.addWidget(self.radioButton_sexeF)
        self.radioButton_sexeH = QtGui.QRadioButton(Dialog)
        self.radioButton_sexeH.setObjectName(_fromUtf8("radioButton_sexeH"))
        self.horizontalLayout_31.addWidget(self.radioButton_sexeH)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_31)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_32.addWidget(self.label_15)
        self.comboBox_nationalite = QtGui.QComboBox(Dialog)
        self.comboBox_nationalite.setObjectName(_fromUtf8("comboBox_nationalite"))
        self.horizontalLayout_32.addWidget(self.comboBox_nationalite)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem5)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_34.addWidget(self.label_16)
        self.radioButton_etudiant_oui = QtGui.QRadioButton(Dialog)
        self.radioButton_etudiant_oui.setObjectName(_fromUtf8("radioButton_etudiant_oui"))
        self.buttonGroup_9 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_9.setObjectName(_fromUtf8("buttonGroup_9"))
        self.buttonGroup_9.addButton(self.radioButton_etudiant_oui)
        self.horizontalLayout_34.addWidget(self.radioButton_etudiant_oui)
        self.radioButton_etudiant_non = QtGui.QRadioButton(Dialog)
        self.radioButton_etudiant_non.setObjectName(_fromUtf8("radioButton_etudiant_non"))
        self.buttonGroup_9.addButton(self.radioButton_etudiant_non)
        self.horizontalLayout_34.addWidget(self.radioButton_etudiant_non)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem6)
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setEnabled(False)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_36.addWidget(self.label_18)
        self.comboBox_discipline = QtGui.QComboBox(Dialog)
        self.comboBox_discipline.setEnabled(False)
        self.comboBox_discipline.setObjectName(_fromUtf8("comboBox_discipline"))
        self.horizontalLayout_36.addWidget(self.comboBox_discipline)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_36)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem7)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setEnabled(False)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_35.addWidget(self.label_17)
        self.comboBox_niveau = QtGui.QComboBox(Dialog)
        self.comboBox_niveau.setEnabled(False)
        self.comboBox_niveau.setObjectName(_fromUtf8("comboBox_niveau"))
        self.horizontalLayout_35.addWidget(self.comboBox_niveau)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem8)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_35)
        self.verticalLayout_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_37.addWidget(self.label_19)
        self.radioButton_expe_oui = QtGui.QRadioButton(Dialog)
        self.radioButton_expe_oui.setObjectName(_fromUtf8("radioButton_expe_oui"))
        self.buttonGroup_10 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_10.setObjectName(_fromUtf8("buttonGroup_10"))
        self.buttonGroup_10.addButton(self.radioButton_expe_oui)
        self.horizontalLayout_37.addWidget(self.radioButton_expe_oui)
        self.radioButton_expe_non = QtGui.QRadioButton(Dialog)
        self.radioButton_expe_non.setObjectName(_fromUtf8("radioButton_expe_non"))
        self.buttonGroup_10.addButton(self.radioButton_expe_non)
        self.horizontalLayout_37.addWidget(self.radioButton_expe_non)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_13.addWidget(self.label_20)
        self.lcdNumber = QtGui.QLCDNumber(Dialog)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_13.addWidget(self.lcdNumber)
        self.horizontalSlider_risques = QtGui.QSlider(Dialog)
        self.horizontalSlider_risques.setMaximum(10)
        self.horizontalSlider_risques.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_risques.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_risques.setObjectName(_fromUtf8("horizontalSlider_risques"))
        self.horizontalLayout_13.addWidget(self.horizontalSlider_risques)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.hl_propositions = QtGui.QHBoxLayout()
        self.hl_propositions.setObjectName(_fromUtf8("hl_propositions"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_cbleuY_oui = QtGui.QRadioButton(Dialog)
        self.radioButton_cbleuY_oui.setObjectName(_fromUtf8("radioButton_cbleuY_oui"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_cbleuY_oui)
        self.horizontalLayout_8.addWidget(self.radioButton_cbleuY_oui)
        self.radioButton_cbleuY_non = QtGui.QRadioButton(Dialog)
        self.radioButton_cbleuY_non.setObjectName(_fromUtf8("radioButton_cbleuY_non"))
        self.buttonGroup.addButton(self.radioButton_cbleuY_non)
        self.horizontalLayout_8.addWidget(self.radioButton_cbleuY_non)
        self.radioButton_cbleuYaut = QtGui.QRadioButton(Dialog)
        self.radioButton_cbleuYaut.setObjectName(_fromUtf8("radioButton_cbleuYaut"))
        self.buttonGroup.addButton(self.radioButton_cbleuYaut)
        self.horizontalLayout_8.addWidget(self.radioButton_cbleuYaut)
        self.lineEdit_cbleuY_precis = QtGui.QLineEdit(Dialog)
        self.lineEdit_cbleuY_precis.setEnabled(True)
        self.lineEdit_cbleuY_precis.setObjectName(_fromUtf8("lineEdit_cbleuY_precis"))
        self.horizontalLayout_8.addWidget(self.lineEdit_cbleuY_precis)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.radioButton_nbatelY1 = QtGui.QRadioButton(Dialog)
        self.radioButton_nbatelY1.setObjectName(_fromUtf8("radioButton_nbatelY1"))
        self.buttonGroup_2 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_nbatelY1)
        self.horizontalLayout_10.addWidget(self.radioButton_nbatelY1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.radioButton_nbatelY2 = QtGui.QRadioButton(Dialog)
        self.radioButton_nbatelY2.setObjectName(_fromUtf8("radioButton_nbatelY2"))
        self.buttonGroup_2.addButton(self.radioButton_nbatelY2)
        self.horizontalLayout_11.addWidget(self.radioButton_nbatelY2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.radioButton_nbatelYaut = QtGui.QRadioButton(Dialog)
        self.radioButton_nbatelYaut.setObjectName(_fromUtf8("radioButton_nbatelYaut"))
        self.buttonGroup_2.addButton(self.radioButton_nbatelYaut)
        self.horizontalLayout_12.addWidget(self.radioButton_nbatelYaut)
        self.lineEdit_nbatelYprecis = QtGui.QLineEdit(Dialog)
        self.lineEdit_nbatelYprecis.setEnabled(True)
        self.lineEdit_nbatelYprecis.setObjectName(_fromUtf8("lineEdit_nbatelYprecis"))
        self.horizontalLayout_12.addWidget(self.lineEdit_nbatelYprecis)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_14.addWidget(self.label_4)
        self.lineEdit_autstrategieY = QtGui.QLineEdit(Dialog)
        self.lineEdit_autstrategieY.setObjectName(_fromUtf8("lineEdit_autstrategieY"))
        self.horizontalLayout_14.addWidget(self.lineEdit_autstrategieY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.hl_propositions.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.hl_propositions)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_15.addWidget(self.label_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_16.addWidget(self.label_6)
        self.radioButton_crougeZ_oui = QtGui.QRadioButton(Dialog)
        self.radioButton_crougeZ_oui.setObjectName(_fromUtf8("radioButton_crougeZ_oui"))
        self.buttonGroup_3 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButton_crougeZ_oui)
        self.horizontalLayout_16.addWidget(self.radioButton_crougeZ_oui)
        self.radioButton_crougeZ_non = QtGui.QRadioButton(Dialog)
        self.radioButton_crougeZ_non.setObjectName(_fromUtf8("radioButton_crougeZ_non"))
        self.buttonGroup_3.addButton(self.radioButton_crougeZ_non)
        self.horizontalLayout_16.addWidget(self.radioButton_crougeZ_non)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_17.addWidget(self.label_7)
        self.radioButton_cbleuZ_oui = QtGui.QRadioButton(Dialog)
        self.radioButton_cbleuZ_oui.setObjectName(_fromUtf8("radioButton_cbleuZ_oui"))
        self.buttonGroup_4 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButton_cbleuZ_oui)
        self.horizontalLayout_17.addWidget(self.radioButton_cbleuZ_oui)
        self.radioButton_cbleuZ_non = QtGui.QRadioButton(Dialog)
        self.radioButton_cbleuZ_non.setObjectName(_fromUtf8("radioButton_cbleuZ_non"))
        self.buttonGroup_4.addButton(self.radioButton_cbleuZ_non)
        self.horizontalLayout_17.addWidget(self.radioButton_cbleuZ_non)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_18.addWidget(self.label_8)
        self.radioButton_cvertZ_oui = QtGui.QRadioButton(Dialog)
        self.radioButton_cvertZ_oui.setObjectName(_fromUtf8("radioButton_cvertZ_oui"))
        self.buttonGroup_5 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.radioButton_cvertZ_oui)
        self.horizontalLayout_18.addWidget(self.radioButton_cvertZ_oui)
        self.radioButton_cvertZ_non = QtGui.QRadioButton(Dialog)
        self.radioButton_cvertZ_non.setObjectName(_fromUtf8("radioButton_cvertZ_non"))
        self.buttonGroup_5.addButton(self.radioButton_cvertZ_non)
        self.horizontalLayout_18.addWidget(self.radioButton_cvertZ_non)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_19.addWidget(self.label_9)
        self.radioButton_c3courbesZ_oui = QtGui.QRadioButton(Dialog)
        self.radioButton_c3courbesZ_oui.setObjectName(_fromUtf8("radioButton_c3courbesZ_oui"))
        self.buttonGroup_6 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.radioButton_c3courbesZ_oui)
        self.horizontalLayout_19.addWidget(self.radioButton_c3courbesZ_oui)
        self.radioButton_c3courbesZ_non = QtGui.QRadioButton(Dialog)
        self.radioButton_c3courbesZ_non.setObjectName(_fromUtf8("radioButton_c3courbesZ_non"))
        self.buttonGroup_6.addButton(self.radioButton_c3courbesZ_non)
        self.horizontalLayout_19.addWidget(self.radioButton_c3courbesZ_non)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_20.addWidget(self.label_10)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.radioButton_cnbatelZ1 = QtGui.QRadioButton(Dialog)
        self.radioButton_cnbatelZ1.setObjectName(_fromUtf8("radioButton_cnbatelZ1"))
        self.buttonGroup_7 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.radioButton_cnbatelZ1)
        self.horizontalLayout_21.addWidget(self.radioButton_cnbatelZ1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.radioButton_cnbatelZ2 = QtGui.QRadioButton(Dialog)
        self.radioButton_cnbatelZ2.setObjectName(_fromUtf8("radioButton_cnbatelZ2"))
        self.buttonGroup_7.addButton(self.radioButton_cnbatelZ2)
        self.horizontalLayout_22.addWidget(self.radioButton_cnbatelZ2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.radioButton_cnbatelZaut = QtGui.QRadioButton(Dialog)
        self.radioButton_cnbatelZaut.setObjectName(_fromUtf8("radioButton_cnbatelZaut"))
        self.buttonGroup_7.addButton(self.radioButton_cnbatelZaut)
        self.horizontalLayout_23.addWidget(self.radioButton_cnbatelZaut)
        self.lineEdit_nbatelZprecis = QtGui.QLineEdit(Dialog)
        self.lineEdit_nbatelZprecis.setEnabled(True)
        self.lineEdit_nbatelZprecis.setObjectName(_fromUtf8("lineEdit_nbatelZprecis"))
        self.horizontalLayout_23.addWidget(self.lineEdit_nbatelZprecis)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_26.addWidget(self.label_11)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.radioButton_cpqZ1 = QtGui.QRadioButton(Dialog)
        self.radioButton_cpqZ1.setObjectName(_fromUtf8("radioButton_cpqZ1"))
        self.buttonGroup_8 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_8.setObjectName(_fromUtf8("buttonGroup_8"))
        self.buttonGroup_8.addButton(self.radioButton_cpqZ1)
        self.horizontalLayout_27.addWidget(self.radioButton_cpqZ1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.radioButton_cpqZ2 = QtGui.QRadioButton(Dialog)
        self.radioButton_cpqZ2.setObjectName(_fromUtf8("radioButton_cpqZ2"))
        self.buttonGroup_8.addButton(self.radioButton_cpqZ2)
        self.horizontalLayout_28.addWidget(self.radioButton_cpqZ2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.radioButton_cpqZaut = QtGui.QRadioButton(Dialog)
        self.radioButton_cpqZaut.setObjectName(_fromUtf8("radioButton_cpqZaut"))
        self.buttonGroup_8.addButton(self.radioButton_cpqZaut)
        self.horizontalLayout_29.addWidget(self.radioButton_cpqZaut)
        self.lineEdit_pqZprecis = QtGui.QLineEdit(Dialog)
        self.lineEdit_pqZprecis.setEnabled(True)
        self.lineEdit_pqZprecis.setObjectName(_fromUtf8("lineEdit_pqZprecis"))
        self.horizontalLayout_29.addWidget(self.lineEdit_pqZprecis)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_26.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_30.addWidget(self.label_12)
        self.lineEdit_autstrategieZ = QtGui.QLineEdit(Dialog)
        self.lineEdit_autstrategieZ.setObjectName(_fromUtf8("lineEdit_autstrategieZ"))
        self.horizontalLayout_30.addWidget(self.lineEdit_autstrategieZ)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout.addLayout(self.verticalLayout_10)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem18)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.pushButton_valider = QtGui.QPushButton(Dialog)
        self.pushButton_valider.setObjectName(_fromUtf8("pushButton_valider"))
        self.horizontalLayout_2.addWidget(self.pushButton_valider)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.horizontalSlider_risques, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber.display)
        QtCore.QObject.connect(self.lineEdit_cbleuY_precis, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.radioButton_cbleuYaut.click)
        QtCore.QObject.connect(self.lineEdit_nbatelYprecis, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.radioButton_nbatelYaut.click)
        QtCore.QObject.connect(self.lineEdit_nbatelZprecis, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.radioButton_cnbatelZaut.click)
        QtCore.QObject.connect(self.lineEdit_pqZprecis, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.radioButton_cpqZaut.click)
        QtCore.QObject.connect(self.radioButton_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_18.setEnabled)
        QtCore.QObject.connect(self.radioButton_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBox_discipline.setEnabled)
        QtCore.QObject.connect(self.radioButton_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_17.setEnabled)
        QtCore.QObject.connect(self.radioButton_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBox_niveau.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_age, self.radioButton_sexeF)
        Dialog.setTabOrder(self.radioButton_sexeF, self.radioButton_sexeH)
        Dialog.setTabOrder(self.radioButton_sexeH, self.comboBox_nationalite)
        Dialog.setTabOrder(self.comboBox_nationalite, self.radioButton_etudiant_oui)
        Dialog.setTabOrder(self.radioButton_etudiant_oui, self.radioButton_etudiant_non)
        Dialog.setTabOrder(self.radioButton_etudiant_non, self.comboBox_discipline)
        Dialog.setTabOrder(self.comboBox_discipline, self.comboBox_niveau)
        Dialog.setTabOrder(self.comboBox_niveau, self.radioButton_expe_oui)
        Dialog.setTabOrder(self.radioButton_expe_oui, self.radioButton_expe_non)
        Dialog.setTabOrder(self.radioButton_expe_non, self.horizontalSlider_risques)
        Dialog.setTabOrder(self.horizontalSlider_risques, self.radioButton_cbleuY_oui)
        Dialog.setTabOrder(self.radioButton_cbleuY_oui, self.radioButton_cbleuY_non)
        Dialog.setTabOrder(self.radioButton_cbleuY_non, self.radioButton_nbatelY1)
        Dialog.setTabOrder(self.radioButton_nbatelY1, self.radioButton_nbatelY2)
        Dialog.setTabOrder(self.radioButton_nbatelY2, self.radioButton_nbatelYaut)
        Dialog.setTabOrder(self.radioButton_nbatelYaut, self.lineEdit_nbatelYprecis)
        Dialog.setTabOrder(self.lineEdit_nbatelYprecis, self.lineEdit_autstrategieY)
        Dialog.setTabOrder(self.lineEdit_autstrategieY, self.radioButton_crougeZ_oui)
        Dialog.setTabOrder(self.radioButton_crougeZ_oui, self.radioButton_crougeZ_non)
        Dialog.setTabOrder(self.radioButton_crougeZ_non, self.radioButton_cbleuZ_oui)
        Dialog.setTabOrder(self.radioButton_cbleuZ_oui, self.radioButton_cbleuZ_non)
        Dialog.setTabOrder(self.radioButton_cbleuZ_non, self.radioButton_cvertZ_oui)
        Dialog.setTabOrder(self.radioButton_cvertZ_oui, self.radioButton_cvertZ_non)
        Dialog.setTabOrder(self.radioButton_cvertZ_non, self.radioButton_c3courbesZ_oui)
        Dialog.setTabOrder(self.radioButton_c3courbesZ_oui, self.radioButton_c3courbesZ_non)
        Dialog.setTabOrder(self.radioButton_c3courbesZ_non, self.radioButton_cnbatelZ1)
        Dialog.setTabOrder(self.radioButton_cnbatelZ1, self.radioButton_cnbatelZ2)
        Dialog.setTabOrder(self.radioButton_cnbatelZ2, self.radioButton_cnbatelZaut)
        Dialog.setTabOrder(self.radioButton_cnbatelZaut, self.lineEdit_nbatelZprecis)
        Dialog.setTabOrder(self.lineEdit_nbatelZprecis, self.radioButton_cpqZ1)
        Dialog.setTabOrder(self.radioButton_cpqZ1, self.radioButton_cpqZ2)
        Dialog.setTabOrder(self.radioButton_cpqZ2, self.radioButton_cpqZaut)
        Dialog.setTabOrder(self.radioButton_cpqZaut, self.lineEdit_pqZprecis)
        Dialog.setTabOrder(self.lineEdit_pqZprecis, self.lineEdit_autstrategieZ)
        Dialog.setTabOrder(self.lineEdit_autstrategieZ, self.pushButton_valider)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Question de compréhension", None))
        self.label_numeroQuestion.setText(_translate("Dialog", "Questionnaire final", None))
        self.label_13.setText(_translate("Dialog", "Quel est votre age ? ", None))
        self.label_14.setText(_translate("Dialog", "Sexe : ", None))
        self.radioButton_sexeF.setText(_translate("Dialog", "Femme", None))
        self.radioButton_sexeH.setText(_translate("Dialog", "Homme", None))
        self.label_15.setText(_translate("Dialog", "Nationalité : ", None))
        self.label_16.setText(_translate("Dialog", "Etes-vous étudiant ? ", None))
        self.radioButton_etudiant_oui.setText(_translate("Dialog", "Oui", None))
        self.radioButton_etudiant_non.setText(_translate("Dialog", "Non", None))
        self.label_18.setText(_translate("Dialog", "Discipline : ", None))
        self.label_17.setText(_translate("Dialog", "Niveau : ", None))
        self.label_19.setText(_translate("Dialog", "Avez-vous déjà participé à une expérience d\'économie ? ", None))
        self.radioButton_expe_oui.setText(_translate("Dialog", "Oui", None))
        self.radioButton_expe_non.setText(_translate("Dialog", "Non", None))
        self.label_20.setText(_translate("Dialog", "Certaines personnes  aiment prendre des risques tandis que d\'autres sont plus réticentes. \n"
"Comment qualifieriez-vous votre attitude par rapport à la prise de risque en général?\n"
"De 0 (Très réticent) à 10 (Très volontaire)", None))
        self.label.setText(_translate("Dialog", "Quelle stratégie avez-vous utilisé pour choisir le niveau d’intrant X pour produire le produit Y (non risqué) ?", None))
        self.label_2.setText(_translate("Dialog", "J’ai cherché à être au maximum de la courbe bleue de profit pour le produit Y :", None))
        self.radioButton_cbleuY_oui.setText(_translate("Dialog", "Oui", None))
        self.radioButton_cbleuY_non.setText(_translate("Dialog", "Non", None))
        self.radioButton_cbleuYaut.setText(_translate("Dialog", "Autre : précisez", None))
        self.label_3.setText(_translate("Dialog", "J’ai cherché à avoir :", None))
        self.radioButton_nbatelY1.setText(_translate("Dialog", "le moins d’ateliers possible pour le produit Y", None))
        self.radioButton_nbatelY2.setText(_translate("Dialog", "le plus d’ateliers possible pour le produit Y", None))
        self.radioButton_nbatelYaut.setText(_translate("Dialog", "Autre : précisez : ", None))
        self.label_4.setText(_translate("Dialog", "Quelle(s) autre(s) stratégie(s) avez-vous suivi pour le produit Y ? Précisez : ", None))
        self.label_5.setText(_translate("Dialog", "Quelle stratégie avez-vous utilisé pour choisir le niveau d’intrant X pour produire le produit Z (risqué) ?", None))
        self.label_6.setText(_translate("Dialog", "Seule la courbe rouge (courbe où le profit est minimum) importait pour moi.  :           ", None))
        self.radioButton_crougeZ_oui.setText(_translate("Dialog", "Oui", None))
        self.radioButton_crougeZ_non.setText(_translate("Dialog", "Non", None))
        self.label_7.setText(_translate("Dialog", "Seule la courbe bleue (courbe où le profit est moyen) importait pour moi .  :              ", None))
        self.radioButton_cbleuZ_oui.setText(_translate("Dialog", "Oui", None))
        self.radioButton_cbleuZ_non.setText(_translate("Dialog", "Non", None))
        self.label_8.setText(_translate("Dialog", "Seule la courbe verte (courbe où le profit est maximum) importait pour moi .:             ", None))
        self.radioButton_cvertZ_oui.setText(_translate("Dialog", "Oui", None))
        self.radioButton_cvertZ_non.setText(_translate("Dialog", "Non", None))
        self.label_9.setText(_translate("Dialog", "J’ai considéré les 3 courbes (rouge, bleue et verte) pour choisir le niveau d’intrant X.:", None))
        self.radioButton_c3courbesZ_oui.setText(_translate("Dialog", "Oui", None))
        self.radioButton_c3courbesZ_non.setText(_translate("Dialog", "Non", None))
        self.label_10.setText(_translate("Dialog", "J’ai cherché à avoir :", None))
        self.radioButton_cnbatelZ1.setText(_translate("Dialog", "le moins d’ateliers possible pour le produit Z", None))
        self.radioButton_cnbatelZ2.setText(_translate("Dialog", "le plus d’ateliers possible pour le produit Z", None))
        self.radioButton_cnbatelZaut.setText(_translate("Dialog", "Autre : précisez : ", None))
        self.label_11.setText(_translate("Dialog", "J’ai préféré :", None))
        self.radioButton_cpqZ1.setText(_translate("Dialog", "modifier le nombre d’ateliers pour le produit Z plutôt que de modifier la quantité d’intrant X pour le produit Z", None))
        self.radioButton_cpqZ2.setText(_translate("Dialog", "modifier la quantité d’intrant X pour le produit Z plutôt que modifier le nombre d’ateliers pour le produit Z", None))
        self.radioButton_cpqZaut.setText(_translate("Dialog", "Autre :  Précisez : ", None))
        self.label_12.setText(_translate("Dialog", "Quelle(s) autre(s) stratégie(s) avez-vous suivi pour le produit Z ? Précisez : ", None))
        self.pushButton_valider.setText(_translate("Dialog", "Valider", None))

